# Generated by Django 2.1.1 on 2018-09-25 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='ID',
            new_name='kickstarter_id',
        ),
    ]
